---
- name: Include variables installation on OS family
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Include installation on OS family
  include: "install.{{ ansible_os_family | lower }}.yml"

- name: Ensure log dir
  file:
    path: /var/log/mysql/
    state: directory
    owner: mysql
    group: adm
    mode: 0775

- name: Create config dir
  file:
    path: "{{ mysql_galera_conf_dir }}/conf.d/"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Modify file for Galera
  template:
    src: galera.cnf.j2
    dest: "{{ mysql_galera_conf_dir }}/conf.d/galera.cnf"
    mode: 0644
    owner: root
    group: root

- name: Stop mysql
  service:
    name: mysql
    state: stopped

- name: Copy mysql file to systemd tmpfiles.d
  copy:
    src: mysql.conf
    dest: /etc/tmpfiles.d
    mode: 0644
    owner: root
    group: root

- name: Copy My.cnf file and change settings
  template:
    src: my.cnf.j2
    dest: "{{ mysql_galera_conf_dir }}/my.cnf"
    mode: 0644
    owner: root
    group: root

- name: Start up first galera node
  command: service mysql bootstrap
  when: first_galera_node==True

- name: Start up the other galera nodes
  command: service mysql start
  when: first_galera_node==False
